apiVersion: batch/v1
kind: Job
metadata:
  name: v0.15.0-upgrade
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.15.1"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: eventing-controller
      restartPolicy: Never
      containers:
      - name: upgrade-brokers
        image: TO_BE_REPLACED

---
